storage: ./storage

plugins: ./plugins

packages:
  "@*/*":
    access: $all
    publish: $all
    unpublish: $authenticated

  "**":
    access: $all
    publish: $all
    unpublish: $authenticated

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    cache: true
    maxage: 30m

web:
  enable: true
  title: Turbo Verdaccio Registry
  logo: https://raw.githubusercontent.com/verdaccio/verdaccio/master/assets/logo/verdaccio.svg

listen:
  - 0.0.0.0:4873

auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1

middlewares:
  audit:
    enabled: true
  cors:
    enabled: true
    origin: "*"
    methods: "GET,HEAD,PUT,PATCH,POST,DELETE"
    preflightContinue: false
    optionsSuccessStatus: 204

logs:
  - { type: stdout, format: pretty, level: http }
  - { type: file, format: pretty, level: http, path: ./verdaccio.log }

max_body_size: 200mb
uplink_timeout: 60s
